version: '3'

services:
  nginx:
    restart: always
    image: nginx
    ports:
    - "80:80"
    volumes:
    - "./nginx:/etc/nginx/conf.d/"
    depends_on:
    - web
  web:
    restart: always
    build: .
    command:
      - /bin/sh
      - -c
      - |
        sleep 8
        python3 manage.py migrate
        gunicorn -w 3 -b 0.0.0.0:8080 Demo.wsgi:application
    ports:
    - "8080:8080"
